[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino

[env:native]
platform = native
test_build_src = yes
build_src_filter =
    +<tempo.cpp>
    +<clock.cpp>
    +<pattern.cpp>
    +<beat_sequence.cpp>
